Repository operate-first/ionos-openshift, pull requests merged in 2022-08, with the labels that each got.

#9 add logs (emails)
  logs/20220804-0726_email_ionos.md
  logs/20220805-0604_email_ionos.md
Labels: size/M

#10 installing a multinode OpenShift cluster with terraform
  .gitignore
  terraform-ocp/README.md
  terraform-ocp/aicli-params.yaml
  terraform-ocp/main.tf
  terraform-ocp/outputs.tf
  terraform-ocp/variables.tf
Labels: size/L

#13 terraform
  terraform-ocp/README.md
  terraform-ocp/dcd.png
Labels: size/XS
